# %shell> docker compose -f ref/dockerfiles/docker-compose.yml up -d
## for development
services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 9999:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - stadium
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - stadium
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - stadium
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_db
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # POSTGRES_INITDB_WALDIR: By default the transaction log is stored in a subdirectory of the main Postgres data folder (PGDATA).
      # POSTGRES_HOST_AUTH_METHOD: If unspecified then md5 password authentication is used.
      # PGDATA
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    networks:
      - stadium
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - type: volume
        source: pgadmin-data
        target: /var/lib/pgadmin



volumes:
  my-data:
  pg-data:
  pgadmin-data:

networks:
  stadium: