env:
  browser: true
  es2022: true
  node: true
extends:
  - standard-with-typescript
  - plugin:svelte/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
  extraFileExtensions:
    - .svelte
overrides:
  - files:
      - "*.svelte"
    parser: svelte-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
ignorePatterns: ["*.cjs"]
rules: {}
