# Generated by Django 4.0.1 on 2022-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0002_guest_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicecameraconnectstatus',
            old_name='camera',
            new_name='device_camera',
        ),
        migrations.RenameField(
            model_name='devicecameraconnectstatus',
            old_name='cube',
            new_name='device_cube',
        ),
        migrations.RenameField(
            model_name='devicecube',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='devicecameraconnectstatus',
            name='modified_time',
            field=models.PositiveBigIntegerField(default=1642139301),
        ),
        migrations.AlterField(
            model_name='devicecameraevent',
            name='created_timestamp',
            field=models.PositiveBigIntegerField(default=1642139301),
        ),
    ]
