# Generated by Django 4.0.1 on 2022-01-13 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCamera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=50)),
                ('device_pw', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'device_camera',
            },
        ),
        migrations.CreateModel(
            name='DeviceCube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=255)),
                ('firmware', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_cube',
            },
        ),
        migrations.CreateModel(
            name='DeviceCubeAlertsGuest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_model.devicecube')),
            ],
            options={
                'db_table': 'device_cube_alerts_guest',
            },
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'threat_event',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('recent_camera_query', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_cubes', models.ManyToManyField(through='ml_model.DeviceCubeAlertsGuest', to='ml_model.DeviceCube')),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.AddField(
            model_name='devicecubealertsguest',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_model.guest'),
        ),
        migrations.CreateModel(
            name='DeviceCameraEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='device_camera_event')),
                ('created_timestamp', models.PositiveBigIntegerField(default=1642081080)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ml_model.devicecamera')),
                ('threat_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ml_model.threatevent')),
            ],
            options={
                'db_table': 'device_camera_event',
            },
        ),
        migrations.CreateModel(
            name='DeviceCameraConnectStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_time', models.PositiveBigIntegerField(default=1642081080)),
                ('is_connected', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_model.devicecamera')),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ml_model.devicecube')),
            ],
            options={
                'db_table': 'device_camera_connect_status',
            },
        ),
        migrations.AddField(
            model_name='devicecamera',
            name='cube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ml_model.devicecube'),
        ),
    ]
