fun main() {
    println("Hello, World")
}  
fun main(args: Array<String>) {
    println(args.contentToString())
}


// /*
//  * This Kotlin source file was generated by the Gradle 'init' task.
//  */
// package wbfw109
// // import wbfw109.Library
// // class Library {
// //     fun someLibraryMethod(): Boolean {
// //         return true
// //     }
// // }

// fun main() {
//     println("Hello, World")
//     val fruits = listOf("banana", "avocado", "apple", "kiwifruit")
//     fruits
//         .filter { it.startsWith("a") }
//         .sortedBy { it }
//         .map { it.uppercase() }
//         .forEach { println(it) }

//     // val temp = Library()
//     // println(temp.someLibraryMethod())
// }  